### ISSUE TITLE
Implement RethinkDB backup

### ISSUE THREAD

**Issue by aknuds1** [muzhack/muzhack#75]
- [x] Write script to backup to S3
- [x] Schedule daily backup
- [x] Monitor that backups happen on schedule

**Comment by hkwid** [comment]
When you install 'boto3' and set up the configuration file, it is easy to upload file to s3!

``` python
import boto3

s3_client = boto3.client('s3')

# Upload the file to S3
s3_client.upload_file('test.txt', 'bucket-name', 'test-remote.txt')
```

**Comment by hkwid** [comment]
First, install the library and set a default region:

```
$ pip install boto3
```

Next, set up credentials (in e.g. ~/.aws/credentials):

```
[default]
aws_access_key_id = YOUR_KEY
aws_secret_access_key = YOUR_SECRET
```

Then, set up a default region (in e.g. ~/.aws/config):

```
[default]
region=eu-central-1
```

**Comment by aknuds1** [comment]
Cool, thx Hiro 😊

**Comment by aknuds1** [comment]
@hkwid Do you want to finish this task? You can pull my latest changes and modify rethinkdb/backup.py to upload the backup to S3.

After that we can think of how to schedule the daily backup.

**Comment by hkwid** [comment]
OK! I do!

**Comment by aknuds1** [comment]
I've implemented daily backup within Tutum stack, and ensured that it sends events to Datadog so we can keep track.
