### ISSUE TITLE
Fix reset password flow

### ISSUE THREAD

**Issue by aknuds1** [muzhack/muzhack#89]
Reset password flow is currently broken - try to fix this.

@hkwid Maybe this would be an interesting task for you Hiro. If you like, we can look at this together, although it might be difficult while I'm away.

**Comment by hkwid** [comment]
OK. I will try to fix it!

**Comment by aknuds1** [comment]
Keep in mind that we'll need to talk about how to do it though, it's complicated.

**Comment by aknuds1** [comment]
I fixed it I think.
