### ISSUE TITLE
Fix Discourse SSO

### ISSUE THREAD

**Issue by aknuds1** [muzhack/muzhack#95]
MuzHack supports [single-sign-on](https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045) with the [Discourse forum](http://forums.muzhack.com/).

It's probably not working with the in-development version of MuzHack, we should test and eventually fix.

**Comment by aknuds1** [comment]
@hkwid Assigning this to you, as it should be a good exercise, but we should talk about how to do it.

**Comment by hkwid** [comment]
OK!

**Comment by aknuds1** [comment]
I fixed it.
